server:
  port: 8080
spring:
  application:
    name: propertysys
  datasource:
    url: jdbc:mysql://localhost:3306/propertysys?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml

jwt:
  SING: "pppp2024" #密钥
  expireTime: 30 #token有效时间 (分钟)
