apiVersion: apps/v1
kind: Deployment
metadata:
  name: propertysys-property
spec:
  replicas: 1
  selector:
    matchLabels:
      app: propertysys-property
  template:
    metadata:
      labels:
        app: propertysys-property
    spec:
      containers:
        - name: propertysys-property
          image: bfker1999/propertysys-property:1.0
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://property-mysql.mysql.database.azure.com:3306/pppp_dbs?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
            - name: SPRING_DATASOURCE_USERNAME
              value: property_admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: Passw@rd

---

apiVersion: v1
kind: Service
metadata:
  name: propertysys-property
spec:
  selector:
    app: propertysys-property
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
