
server:
  port: 8082
  servlet:
    context-path: /property

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG


spring:
  application:
    name: propertysys-property
  profiles:
    active: dev

