server:
  port: 8081
  servlet:
    context-path: /user
spring:
  application:
    name: propertysys-user
  datasource:
    url: jdbc:mysql://property-mysql.mysql.database.azure.com:3306/pppp_dbs?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: property_admin
    password: Passw@rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:/mapper/*.xml

jwt:
  SING: "pppp2024" #密钥
  expireTime: 30 #token有效时间 (分钟)

file:
  storage:
    avatar-path: /var/www/propertysys/user/avatars/
  base-url:
    avatar: http://20.2.248.160:8081/user/avatars/

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    path: /var/log/propertysys-user
